[package]
name = "sui-transaction-builder"
version = "0.0.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "BSD-3-Clause-Clear"
publish = false
edition = "2021"

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
futures.workspace = true
bcs.workspace = true

move-binary-format.workspace = true
sui-json-rpc-types.workspace = true
sui-types.workspace = true
sui-json.workspace = true
sui-protocol-config.workspace = true

move-core-types.workspace = true
workspace-hack.workspace = true
