[package]
name = "sui-test-transaction-builder"
version = "0.1.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "BSD-3-Clause-Clear"
publish = false
edition = "2021"

[dependencies]
bcs.workspace = true

shared-crypto.workspace = true
sui-genesis-builder.workspace = true
sui-move-build.workspace = true
sui-sdk.workspace = true
sui-types.workspace = true

move-core-types.workspace = true
workspace-hack.workspace = true
