[[packages]]
source = "Repository"
[packages.values]
repository = "https://github.com/mystenlabs/sui"
branch = "framework/mainnet"
network = "mainnet"
packages = [
    { path = "crates/sui-framework/packages/deepbook", watch = "0xdee9" },
    { path = "crates/sui-framework/packages/move-stdlib", watch = "0x1" },
    { path = "crates/sui-framework/packages/dwallet-framework", watch = "0x2" },
    { path = "crates/sui-framework/packages/dwallet-system", watch = "0x3" },
]

[[packages]]
source = "Repository"
[packages.values]
repository = "https://github.com/mystenlabs/sui"
branch = "framework/testnet"
network = "testnet"
packages = [
    { path = "crates/sui-framework/packages/deepbook", watch = "0xdee9" },
    { path = "crates/sui-framework/packages/move-stdlib", watch = "0x1" },
    { path = "crates/sui-framework/packages/dwallet-framework", watch = "0x2" },
    { path = "crates/sui-framework/packages/dwallet-system", watch = "0x3" },
]

[[packages]]
source = "Repository"
[packages.values]
repository = "https://github.com/mystenlabs/sui"
branch = "framework/devnet"
network = "devnet"
packages = [
    { path = "crates/sui-framework/packages/deepbook", watch = "0xdee9" },
    { path = "crates/sui-framework/packages/move-stdlib", watch = "0x1" },
    { path = "crates/sui-framework/packages/dwallet-framework", watch = "0x2" },
    { path = "crates/sui-framework/packages/dwallet-system", watch = "0x3" },
]

[[packages]]
source = "Repository"
[packages.values]
repository = "https://github.com/mystenlabs/apps"
branch = "main"
network = "mainnet"
packages = [
    { path = "kiosk" },
]

[[packages]]
source = "Repository"
[packages.values]
repository = "https://github.com/mystenlabs/apps"
branch = "testnet"
network = "testnet"
packages = [
    { path = "kiosk" },
]

[[packages]]
source = "Repository"
[packages.values]
repository = "https://github.com/kunalabs-io/sui-smart-contracts"
branch = "master"
packages = [
    { path = "kai-finance" }
]
