[package]
name = "typed-store-derive"
version = "0.3.0"
license = "BSD-3-Clause-Clear"
authors = ["Ade A. <ade@mystenlabs.com>"]
description = "macros for the typed-store crate"
repository = "https://github.com/mystenlabs/mysten-infra"
edition = "2021"
publish = false

[lib]
proc-macro = true

[dependencies]
proc-macro2.workspace = true
quote.workspace = true
syn.workspace = true
workspace-hack.workspace = true

[dev-dependencies]
eyre.workspace = true
rocksdb.workspace = true
tempfile.workspace = true
tokio = { workspace = true, features = ["test-util"] }
typed-store.workspace = true
