[package]
name = "sui-transaction-checks"
version = "0.1.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "BSD-3-Clause-Clear"
publish = false
edition = "2021"

[dependencies]
once_cell.workspace = true
sui-macros.workspace = true
sui-config.workspace = true
sui-protocol-config.workspace = true
sui-types.workspace = true
tracing.workspace = true
sui-execution.workspace = true
fastcrypto-zkp.workspace = true
workspace-hack.workspace = true
