[package]
name = "shared-crypto"
version = "0.0.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "BSD-3-Clause-Clear"
publish = false
edition = "2021"

[dependencies]
serde.workspace = true
serde_repr.workspace = true
fastcrypto = { workspace = true, features = ["copy_key"] }
eyre.workspace = true
bcs.workspace = true
workspace-hack.workspace = true
