packages:
  - 'sdk/**'
  - 'apps/**'
  - 'dapps/**'
  - 'test/sdk/**'
  - '!**/dist/**'
  - '!**/.next/**'
  - '!sdk/create-dapp/templates'
  - '!sdk/typescript/*/**'
  - '!sdk/typescript/scripts'
  - '!sdk/typescript/builder'
  - '!sdk/typescript/cryptography'
  - '!sdk/typescript/signature-mpc'
  - '!sdk/typescript/faucet'
  - '!sdk/typescript/transactions'
  - '!sdk/typescript/client'
  - '!sdk/typescript/verify'
  - '!sdk/typescript/multisig'
  - '!sdk/typescript/utils'
  - '!sdk/typescript/bcs'
  - '!sdk/typescript/zklogin'
  - '!sdk/enoki/react'
  - '!sdk/move-binary-format-wasm/pkg'
  - 'state-proofs/sui/sdk'
