[package]
name = "sui-source-validation"
version = "0.1.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "BSD-3-Clause-Clear"
publish = false
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
anyhow.workspace = true
thiserror.workspace = true
futures.workspace = true

sui-json-rpc-types.workspace = true
sui-types.workspace = true
sui-sdk.workspace = true
sui-move-build.workspace = true

move-binary-format.workspace = true
move-compiler.workspace = true
move-core-types.workspace = true
move-package.workspace = true
move-symbol-pool.workspace = true
workspace-hack.workspace = true

[dev-dependencies]

expect-test.workspace = true
rand.workspace = true
tempfile.workspace = true
tokio = { workspace = true, features = ["macros", "test-util"] }
tracing.workspace = true

sui-test-transaction-builder.workspace = true
test-cluster.workspace = true
