[package]
name = "sui-single-node-benchmark"
version = "0.1.0"
edition = "2021"
publish = false
license = "BSD-3-Clause-Clear"

[dependencies]
move-binary-format.workspace = true
move-bytecode-utils.workspace = true
move-core-types.workspace = true
sui-config.workspace = true
sui-core = { workspace = true, features = ["test-utils"] }
sui-test-transaction-builder.workspace = true
sui-transaction-checks.workspace = true
sui-types = { workspace = true, features = ["test-utils"] }
sui-storage.workspace = true

async-trait.workspace = true
bcs.workspace = true
clap.workspace = true
futures.workspace = true
prometheus.workspace = true
once_cell.workspace = true
strum.workspace = true
strum_macros.workspace = true
telemetry-subscribers.workspace = true
tokio = { workspace = true, features = ["full", "tracing", "test-util"] }
tracing.workspace = true
workspace-hack.workspace = true

[dev-dependencies]
move-package.workspace = true
sui-macros.workspace = true
sui-protocol-config.workspace = true
sui-simulator.workspace = true
