[package]
name = "signature-mpc"
authors = ["dWallet Labs, Ltd. <dev@dwalletlabs.com>"]
license = "BSD-3-Clause-Clear"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]

rand = { version = "0.8", features = ["std"] }
rand_core = { version = "0.6", features = ["std"] }

twopc_mpc = { git = "https://github.com/dwallet-labs/2pc-mpc.git", features = ["secp256k1", "bulletproofs", "paillier"] }
crypto-bigint = { version = "0.5", features = ["rand_core", "serde"], default-features = false }
group = { git = "https://github.com/dwallet-labs/group.git" }
proof = { git = "https://github.com/dwallet-labs/proof.git" }
homomorphic_encryption = { git = "https://github.com/dwallet-labs/homomorphic-encryption.git" }
commitment = { git = "https://github.com/dwallet-labs/commitment.git" }
maurer = { git = "https://github.com/dwallet-labs/maurer.git" }
enhanced_maurer = { git = "https://github.com/dwallet-labs/enhanced-maurer.git" }
tiresias = { git = "https://github.com/dwallet-labs/tiresias.git", features = ["test_exports"] }
ecdsa = { version = "0.16.9", features = ["verifying"] }
# todo: ?
k256 = { git = 'https://github.com/ycscaly/elliptic-curves.git', branch = "13.3-fixed", features = ["arithmetic", "critical-section", "precomputed-tables", "serde", "ecdsa", "hash2curve", "alloc"], default-features = false }

serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }

thiserror = "1.0"

workspace-hack.workspace = true
bcs.workspace = true
sha3 = "0.10.8"
anyhow.workspace = true

[dev-dependencies]
hex = "0.4.3"
