[package]
name = "MainPackage"
version = "0.0.1"

[dependencies]
dWallet = { local = "../../../../crates/sui-framework/packages/dwallet-framework" }
DepPackage = { local = "../dep_package" }

[addresses]
main_package = "0x0"
