[package]
name = "consensus-config"
version = "0.1.0"
license = "BSD-3-Clause-Clear"
authors = ["Mysten Labs <build@mystenlabs.com>"]
edition = "2021"
publish = false

[dependencies]
fastcrypto.workspace = true
multiaddr.workspace = true
rand.workspace = true
serde.workspace = true
shared-crypto.workspace = true

workspace-hack.workspace = true

[dev-dependencies]
insta.workspace = true
