[package]
name = "eth-light-client"
edition = "2021"
version.workspace = true

[dependencies]
helios.workspace = true
sui-sdk.workspace = true
anyhow.workspace = true
serde.workspace = true
ethers.workspace = true
eyre.workspace = true
log = "0.4.21"
bcs.workspace = true