[package]
name = "message-digest"
edition = "2021"
version.workspace = true

[dependencies]
group.workspace = true
bcs = "0.1.6"
base64.workspace = true
serde.workspace = true
schemars.workspace = true
anyhow.workspace = true
dwallet-mpc-types.workspace = true
k256.workspace = true
sha2 = "0.11.0-rc.0"
sha3 = "0.11.0-rc.0"

[lints]
workspace = true
