error[Ika E01001]: invalid object construction
   ┌─ tests/ika_mode/id_leak/through_call_with_borrow_field.move:11:9
   │
11 │         Object { id }
   │         ^^^^^^^^^^^^^
   │         │        │
   │         │        The UID must come directly from ika::object::new. Or for tests, it can come from ika::test_scenario::new_object
   │         Invalid object creation without a newly created UID.

