[package]
name = "typed-store-error"
version = "0.4.0"
license = "BSD-3-Clause-Clear"
authors = ["Ade A. <ade@mystenlabs.com>"]
description = "error types for typed-store crate"
edition = "2021"
publish = false

[dependencies]
serde.workspace = true
thiserror.workspace = true
workspace-hack.workspace = true

