[package]
name = "move-stackless-bytecode-interpreter"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
publish = false
edition = "2021"
license = "BSD-3-Clause-Clear"

[dependencies]
# diem dependencies
move-stackless-bytecode.workspace = true
bytecode-interpreter-crypto.workspace = true
move-binary-format.workspace = true
move-core-types.workspace = true
move-model.workspace = true

# external dependencies
anyhow.workspace = true
codespan-reporting.workspace = true
itertools.workspace = true
num.workspace = true
clap.workspace = true

[dev-dependencies]
datatest-stable.workspace = true
move-prover-test-utils.workspace = true
