[package]
name = "FungibleTokens"
version = "0.0.1"

[dependencies]
dWallet = { local = "../../../crates/sui-framework/packages/dwallet-framework" }

[addresses]
fungible_tokens = "0x0"
abc = "0x0"
rc = "0x0"
