[package]
name = "Tutorial"
version = "0.0.1"

[dependencies]
MoveStdlib = { local = "../../../crates/sui-framework/packages/move-stdlib/" }
dWallet = { local = "../../../crates/sui-framework//packages/sui-framework" }

[addresses]
tutorial = "0x0"
