processed 3 tasks

init:
A: object(0,0), B: object(0,1)

task 1, lines 8-9:
//# programmable --sender A --inputs @B
//> TransferObjects([Gas], Input(0))
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 988000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, line 11:
//# view-object 0,0
Owner: Account Address ( B )
Version: 2
Contents: pera::coin::Coin<pera::pera::PERA> {
    id: pera::object::UID {
        id: pera::object::ID {
            bytes: fake(0,0),
        },
    },
    balance: pera::balance::Balance<pera::pera::PERA> {
        value: 299999998012000u64,
    },
}
