[package]
name = "bytecode-interpreter-testsuite"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
publish = false
edition = "2021"
license = "BSD-3-Clause-Clear"

[dev-dependencies]

# diem dependencies
move-stackless-bytecode-interpreter.workspace = true
move-command-line-common.workspace = true
move-prover-test-utils.workspace = true
move-stdlib.workspace = true
move-unit-test.workspace = true

# external dependencies
anyhow.workspace = true
datatest-stable.workspace = true

[[test]]
name = "concrete_check_testsuite"
harness = false

[dependencies]
