[package]
name = "sui-move-natives-latest"
version = "0.1.0"
edition = "2021"
authors = ["Mysten Labs <eng@mystenlabs.com>"]
description = "Move framework for sui platform"
license = "BSD-3-Clause-Clear"
publish = false

[dependencies]
better_any.workspace = true
bcs.workspace = true
indexmap.workspace = true
smallvec.workspace = true

fastcrypto-zkp.workspace = true
fastcrypto.workspace = true
move-binary-format.workspace = true
move-core-types.workspace = true
move-vm-types.workspace = true

move-stdlib = { path = "../../../external-crates/move/crates/move-stdlib" }
move-vm-runtime = { path = "../../../external-crates/move/crates/move-vm-runtime" }

sui-protocol-config.workspace = true
sui-types.workspace = true
workspace-hack.workspace = true
tracing.workspace = true
ethers.workspace = true
sha3.workspace = true
serde.workspace = true
serde_json.workspace = true
helios.workspace = true
sui-json.workspace = true
signature-mpc.workspace = true
