[package]
name = "x"
version = "0.1.0"
license = "BSD-3-Clause-Clear"
publish = false
edition = "2021"

[dependencies]
anyhow.workspace = true
nexlint.workspace = true
nexlint-lints.workspace = true
clap.workspace = true
