[package]
name = "move-ir-compiler"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
description = "Move IR to bytecode compiler"
repository = "https://github.com/diem/diem"
homepage = "https://diem.com"
license = "BSD-3-Clause-Clear"
publish = false
edition = "2021"

[dependencies]
anyhow.workspace = true
move-bytecode-verifier.workspace = true
move-command-line-common.workspace = true
move-ir-to-bytecode.workspace = true
move-bytecode-source-map.workspace = true
move-binary-format.workspace = true
clap.workspace = true
serde_json.workspace = true

bcs.workspace = true

[features]
default = []
