[package]
name = "sui-cost"
version = "0.1.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "BSD-3-Clause-Clear"
publish = false
edition = "2021"

[dependencies]
sui-types.workspace = true
anyhow.workspace = true
tokio = { workspace = true, features = ["full"] }
serde.workspace = true
strum.workspace = true
strum_macros.workspace = true
bcs.workspace = true
workspace-hack.workspace = true

[dev-dependencies]
insta.workspace = true
test-cluster.workspace = true
sui-config.workspace = true
sui-swarm-config.workspace = true
sui-test-transaction-builder.workspace = true
sui-move-build.workspace = true
move-cli.workspace = true
move-disassembler.workspace = true
sui-json-rpc-types.workspace = true
