[package]
name = "ika-protocol-config"
version = "0.1.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "BSD-3-Clause-Clear"
publish = false
edition = "2024"

[lints]
workspace = true

[dependencies]
serde.workspace = true
tracing.workspace = true
serde_with.workspace = true
sui-protocol-config-macros.workspace = true
schemars.workspace = true
insta.workspace = true
clap.workspace = true
serde-env.workspace = true

[dev-dependencies]
insta.workspace = true
