[package]
name = "sui-macros"
version = "0.7.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "BSD-3-Clause-Clear"
publish = false
edition = "2021"

[dependencies]
sui-proc-macros.workspace = true
once_cell.workspace = true
futures.workspace = true
tracing.workspace = true
workspace-hack.workspace = true
