{
 "title": "Pera Validators - Narwhal",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Environment", "label": "Datasource", "query": "prometheus" },
   { "name": "network", "label": "Network", "query": { "query": "label_values(uptime,network)" } },
   {
    "name": "validator",
    "label": "Validator",
    "query": {
     "query": "label_values(uptime{network=\"$network\"},job)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Health overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Percentage of stake that increments consensus rounds",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(current_voting_right{job=~\"$validator\", network=\"$network\"} and rate(current_round{job=~\"$validator\", network=\"$network\"}[$__interval]) > 0) / 10000",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Current round growth speed",
   "type": "timeseries",
   "description": "The rate of the current round growth. This is reported by the proposer - which forms the next header to be broadcasted by a node.",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "sum by(job) (rate(current_round{job=~\"$validator\", network=\"$network\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current round (timeline)",
   "type": "timeseries",
   "description": "The current round the node is in. This is reported by the proposer - which forms the next header to be broadcasted by a node. The numbers across the nodes shouldn't differ much - if not the same.",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "sum by(host) (current_round{network=\"$network\", job=~\"$validator\"})",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Voting power distribution",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "current_voting_right{job=~\"$validator\", network=\"$network\"} / 10000"
    }
   ]
  },
  {
   "title": "Current Epoch",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 11 },
   "targets": [
    {
     "expr": "current_epoch{job=~\"$validator\", network=\"$network\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Primary network connectivity",
   "type": "timeseries",
   "description": "Num of primary peers connected per host",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 11 },
   "targets": [
    {
     "expr": "sum by (host) (primary_network_peer_connected{job=~\"$validator\", network=\"$network\", type=\"other_primary\"})",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Last commit round lag",
   "type": "status-history",
   "description": "Shows the lag (diff) between the median reported last committed round and the specific host's last committed round. The color scheme shows how far behind nodes are.",
   "gridPos": { "h": 25, "w": 8, "x": 0, "y": 21 },
   "targets": [
    {
     "conditions": [
      {
       "evaluator": {
        "params": [
         0,
         0
        ],
        "type": "gt"
       },
       "operator": { "type": "and" },
       "query": {
        "params": []
       },
       "reducer": {
        "params": [],
        "type": "avg"
       },
       "type": "query"
      }
     ],
     "expression": "$B - $A",
     "reducer": "max",
     "type": "math"
    }
   ]
  },
  {
   "title": "Nodes proposing certified headers",
   "type": "status-history",
   "description": "The nodes that are proposing in rounds during time. When a node advances a round then this will be a green box with \"YES\" text in it. Otherwise a red box with \"NO\" text will be rendered",
   "gridPos": { "h": 25, "w": 8, "x": 8, "y": 21 },
   "targets": [
    {
     "expr": "sum by (job) (rate(certificates_created{network=~\"$network\", job=~\"$validator\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Primary connected to other primaries (number)",
   "type": "status-history",
   "gridPos": { "h": 25, "w": 8, "x": 16, "y": 21 },
   "targets": [
    {
     "expr": " sum by(job) (primary_network_peer_connected{job=~\"$validator\", network=\"$network\", type=\"other_primary\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "NW behavior from Pera POV", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Input / output rate",
   "type": "timeseries",
   "description": "Consensus ordering attempts per sec",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "quantile(0.5, sum by (job) (rate(sequencing_certificate_attempt{job=~\"$validator\",network=\"$network\"}[5m])))",
     "legendFormat": "Consensus adapter input rate"
    },
    {
     "expr": "quantile(0.5, sum (rate(sequencing_acknowledge_latency_count{job=~\"$validator\",network=\"$network\"}[5m])))",
     "legendFormat": "NW input rate"
    },
    {
     "expr": "quantile(0.5, sum by (host) (rate(consensus_handler_processed{host=~\"$validator\", network=\"$network\"}[5m])))",
     "legendFormat": "NW output rate"
    }
   ]
  },
  {
   "title": "p50 and p95 Consensus Adapter e2e latency",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "clamp(quantile(0.67, histogram_quantile(0.5, sum(rate(sequencing_certificate_latency_bucket{job=~\"$validator\", network=\"$network\"}[5m])) by(job, le))), 0, 30)",
     "legendFormat": "p50"
    },
    {
     "expr": "clamp(quantile(0.67, histogram_quantile(0.95, sum(rate(sequencing_certificate_latency_bucket{job=~\"$validator\", network=\"$network\"}[5m])) by(job, le))), 0, 30)",
     "legendFormat": "p95"
    }
   ]
  },
  {
   "title": "Submission amplification",
   "type": "timeseries",
   "description": "Percentage of requests that got submitted more than once",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum (rate(sequencing_certificate_latency_count{job=~\"$validator\", network=\"$network\", position=\"1\"}[5m]))\n/\nsum (rate(sequencing_certificate_latency_count{job=~\"$validator\", network=\"$network\", position!=\"not_submitted\"}[5m]))",
     "legendFormat": "Attempt #2"
    },
    {
     "expr": "sum (rate(sequencing_certificate_latency_count{job=~\"$validator\", network=\"$network\", position=\"2\"}[5m]))\n/\nsum (rate(sequencing_certificate_latency_count{job=~\"$validator\", network=\"$network\", position!=\"not_submitted\"}[5m]))",
     "legendFormat": "Attempt #3"
    },
    {
     "expr": "sum (rate(sequencing_certificate_latency_count{job=~\"$validator\", network=\"$network\", position=\"3\"}[5m]))\n/\nsum (rate(sequencing_certificate_latency_count{job=~\"$validator\", network=\"$network\", position!=\"not_submitted\"}[5m]))",
     "legendFormat": "Attempt #4"
    },
    {
     "expr": "sum (rate(sequencing_certificate_latency_count{host=~\"$validator\", network=\"$network\", position=\"4\"}[5m]))\n/\nsum (rate(sequencing_certificate_latency_count{host=~\"$validator\", network=\"$network\", position!=\"not_submitted\"}[5m]))",
     "legendFormat": "Attempt #5"
    },
    {
     "expr": "sum (rate(sequencing_certificate_latency_count{host=~\"$validator\", network=\"$network\", position!~\"(0|1|2|3|4|not_submitted)\"}[5m]))\n/\nsum (rate(sequencing_certificate_latency_count{host=~\"$validator\", network=\"$network\", position!=\"not_submitted\"}[5m]))",
     "legendFormat": "Attempt #6+"
    }
   ]
  },
  {
   "title": "Submission rate by authority",
   "type": "timeseries",
   "description": "Ideally we want the low-score NW validators to not submit transactions",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (job) (rate(sequencing_acknowledge_latency_count{job=~\"$validator\",network=\"$network\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg score per host",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 57 },
   "targets": [
    {
     "expr": "avg by (authority) (consensus_handler_scores{job=~\"$validator\", network=\"$network\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Score per host change",
   "type": "state-timeline",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 57 },
   "targets": [
    {
     "expr": "avg by (authority) (consensus_handler_scores{job=~\"$validator\", network=\"$network\"})",
     "legendFormat": "{{authority}}"
    }
   ]
  },
  {
   "title": "Num low scoring authorities",
   "type": "timeseries",
   "description": "As reported by consensus handler to every host",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 67 },
   "targets": [
    {
     "expr": "avg by (job) (consensus_handler_num_low_scoring_authorities{network=\"$network\", job=~\"$validator\"})",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Num of bad nodes",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 67 },
   "targets": [
    {
     "expr": "avg by (job) (num_of_bad_nodes{network=\"$network\", job=~\"$validator\"})",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "p95: txn to commit stacked breakdown",
   "type": "timeseries",
   "description": "This is a median value across validators",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "quantile(0.5, histogram_quantile(0.95, sum by(le, job) (rate(created_batch_latency_bucket{job=~\"$validator\", network=\"$network\"}[5m]))))",
     "legendFormat": "batch_creation"
    },
    {
     "expr": "quantile(0.5, histogram_quantile(0.95, sum by(le, job) (rate(proposer_batch_latency_bucket{job=~\"$validator\",network=\"$network\"}[5m]))))",
     "legendFormat": "batch_to_header"
    },
    {
     "expr": "quantile(0.5, histogram_quantile(0.95, sum by(job,le) (rate(header_to_certificate_latency_bucket{job=~\"$validator\",network=\"$network\"}[5m]))))",
     "legendFormat": "header_to_cert"
    },
    {
     "expr": "quantile(0.5, histogram_quantile(0.95, sum by(job,le) (rate(certificate_commit_latency_bucket{job=~\"$validator\",network=\"$network\"}[5m]))))",
     "legendFormat": "cert_to_commit"
    }
   ]
  },
  {
   "title": "Inflight submissions per validator",
   "type": "timeseries",
   "description": "Individual submissions by each authority",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 77 },
   "targets": [
    {
     "expr": "quantile(0.5, sequencing_in_flight_submissions{network=\"$network\", job=~\"$validator\"})",
     "legendFormat": "p50"
    },
    {
     "expr": "quantile(0.75, sequencing_in_flight_submissions{network=\"$network\", job=~\"$validator\"})",
     "legendFormat": "p75"
    }
   ]
  },
  {
   "title": "Consensus Adapter latency estimates",
   "type": "timeseries",
   "description": "Each authority is doing latency estimates in order to determine the retry intervals.",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    {
     "expr": "clamp(sequencing_estimated_latency{job=~\"$validator\", network=\"$network\"}, 0, 60000)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Consensus Handler Utilization",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 77 },
   "targets": [
    {
     "expr": "avg by (name) (sum by(job,name) (rate(monitored_scope_duration_ns{job=~\"$validator\", network=\"$network\", name=~\"HandleConsensusOutput|HandleConsensusTransaction|VerifyConsensusTransaction\"}[5m])) / 1000000000)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Channel and Critical Section Utilizations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 87 }
  },
  {
   "title": "Internal channels throughput",
   "type": "timeseries",
   "description": "Num of processed entries per sec per validator",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 88 },
   "targets": [
    {
     "expr": "sum by (job,channel) (rate(label_replace({__name__=~\"tx.*total\", job=~\"$validator\",network=\"$network\"},\"channel\",\"$1\",\"__name__\", \"(.+)\")[5m:])) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Internal channels: num pending elements",
   "type": "timeseries",
   "description": "Num of pending entries per channel per validator",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 88 },
   "targets": [
    {
     "expr": "sum by (job,channel) (label_replace({__name__=~\"tx_.*\", __name__!~\"tx.*total\", job=~\"$validator\",network=\"$network\"}, \"channel\", \"$1\", \"__name__\", \"(.+)\"))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Critical Section Load",
   "type": "timeseries",
   "description": "When we receive a certificate for processing we are checking for their parents in our internal storage. If we are missing those, we suspend the processing (with reason \"missing_parents\") and we are trying to fetch those from the other primary nodes. The processing of the certificate resumes only when all their parents are fetched.",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 88 },
   "targets": [
    {
     "expr": "avg by (name) (sum by(job,name) (rate(monitored_scope_duration_ns{job=~\"$validator\", network=\"$network\", name!~\"CheckpointNotifyRead|ValidateBatch\"}[5m])) / 1000000000)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Consensus Advance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 99 } },
  {
   "title": "Pct of rounds that fail to commit",
   "type": "timeseries",
   "description": "All the even rounds that failed to commit because of leader not found or not supported",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum (rate(leader_election{job=~\"$validator\", network=\"$network\", outcome=\"not_found\"}[5m])) / sum (rate(leader_election{job=~\"$validator\", network=\"$network\"}[5m]))",
     "legendFormat": "Leader not found"
    },
    {
     "expr": "sum (rate(leader_election{job=~\"$validator\", network=\"$network\", outcome=\"not_enough_support\"}[5m])) / sum (rate(leader_election{job=~\"$validator\", network=\"$network\"}[5m]))",
     "legendFormat": "Not enough support for leader"
    }
   ]
  },
  {
   "title": "Last committed round",
   "type": "timeseries",
   "description": "The latest committed round by consensus. On a healthy cluster those numbers shouldn't differ much from each other - if not being almost the exact same",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 100 },
   "targets": [
    {
     "expr": "sum by(host) (last_committed_round{host=~\"$validator\",network=\"$network\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Commit round depth",
   "type": "timeseries",
   "description": "Delta between current round and last committed round. Should not grow.",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 100 },
   "targets": [
    {
     "expr": "sum by (job) (current_round) - sum by (job) (last_committed_round{job=~\"$validator\",network=\"$network\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last committed round",
   "type": "table",
   "description": "The latest committed round by consensus. On a healthy cluster those numbers shouldn't differ much from each other - if not being almost the exact same",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 110 },
   "targets": [
    {
     "expr": "sum by(job) (last_committed_round{job=~\"$validator\",network=\"$network\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average interval of NW rounds and p95 NW commits",
   "type": "timeseries",
   "description": "In a perfect case every even NW round should generate a commit.",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(consensus_commit_rounds_latency_bucket{network=~\"$network\", job=~\"$validator\"}[5m])) by (le))",
     "legendFormat": "{{host}}-commit"
    },
    {
     "expr": "1 / rate(current_round{job=~\"$validator\", network=\"$network\"}[5m])",
     "legendFormat": "{{host}}-round"
    }
   ]
  },
  {
   "title": "NW cert distribution per committed sub-dag",
   "type": "timeseries",
   "description": "The number of NW certificates in the committed sub-dag",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 110 },
   "targets": [
    {
     "expr": "committed_certificates{job=~\"$validator\",network=\"$network\",pct=\"50\"}",
     "legendFormat": "{{host}}-p50"
    },
    {
     "expr": "committed_certificates{job=~\"$validator\",network=\"$network\",pct=\"95\"}",
     "legendFormat": "{{host}}-p95"
    }
   ]
  },
  { "title": "Data dissemination", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 120 } },
  {
   "title": "Average num of certificates per batch",
   "type": "timeseries",
   "description": "Since both certs and batches are processed in the consensus handler we can do the math",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 121 },
   "targets": [
    {
     "expr": "sum by (job) (rate(consensus_handler_processed{job=~\"$validator\", network=\"$network\"}[5m]))\n/\nsum by (job) (rate(consensus_handler_processed_batches{job=~\"$validator\",network=\"$network\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Batch generation latency",
   "type": "timeseries",
   "description": "Batch composition, sealing and delivering to the primary",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 121 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(created_batch_latency_bucket{job=~\"$validator\",network=\"$network\"}[5m])))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(created_batch_latency_bucket{job=~\"$validator\",network=\"$network\"}[5m])))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "Batch size distribution",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 121 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.05, sum(rate(created_batch_size_bucket{job=~\"$validator\",network=\"$network\"}[5m])) by (le))",
     "legendFormat": "p05"
    },
    {
     "expr": "histogram_quantile(0.25, sum(rate(created_batch_size_bucket{job=~\"$validator\",network=\"$network\"}[5m])) by (le))",
     "legendFormat": "p25"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(created_batch_size_bucket{job=~\"$validator\",network=\"$network\"}[5m])) by (le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(created_batch_size_bucket{job=~\"$validator\",network=\"$network\"}[5m])) by (le))",
     "legendFormat": "p75"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(created_batch_size_bucket{job=~\"$validator\",network=\"$network\"}[5m])) by (le))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Inflight Batches ",
   "type": "timeseries",
   "description": "Each batch should be delivered to 2f+1 of other workers prior to further processing",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 132 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "parallel_worker_batches{job=~\"$validator\",network=\"$network\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Proposer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 143 } },
  {
   "title": "Batch to Header Latency",
   "type": "timeseries",
   "description": "Time between batch creation and the moment it's included in a header proposal (both p50 and p95 are medians across validators).",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 144 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "quantile(0.5, histogram_quantile(0.5, sum by(le, job) (rate(proposer_batch_latency_bucket{job=~\"$validator\",network=\"$network\"}[5m]))))",
     "legendFormat": "p50"
    },
    {
     "expr": "quantile(0.5, histogram_quantile(0.95, sum by(le, job) (rate(proposer_batch_latency_bucket{job=~\"$validator\",network=\"$network\"}[5m]))))",
     "legendFormat": "p95"
    }
   ]
  },
  {
   "title": "Num of pending batches in proposer",
   "type": "timeseries",
   "description": "The number of batches waiting to be included in headers in the proposer. A high number shows that batches are not assigned to headers - or the proposed headers don't make it to a successful commit , thus they are returned back to the proposer for re-proposal",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 144 },
   "targets": [
    {
     "expr": "quantile(0.5, sum by(job) (num_of_pending_batches_in_proposer{network=\"$network\", job=~\"$validator\"}))",
     "legendFormat": "pct50"
    },
    {
     "expr": "quantile(0.95, sum by(job) (num_of_pending_batches_in_proposer{network=\"$network\", job=~\"$validator\"}))",
     "legendFormat": "pct95"
    }
   ]
  },
  {
   "title": "Num batches per header",
   "type": "timeseries",
   "description": "The distribution of the batches per header across the validators.",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 144 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (reason, le) (rate(num_of_batch_digests_in_header_bucket{job=~\"$validator\", network=\"$network\"}[5m])))",
     "legendFormat": "{{reason}}-p50"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (reason, le) (rate(num_of_batch_digests_in_header_bucket{job=~\"$validator\", network=\"$network\"}[5m])))",
     "legendFormat": "{{reason}}-p95"
    }
   ]
  },
  {
   "title": "Certificate to Commit Latency",
   "type": "timeseries",
   "description": "The time it takes for a certificate from the moment it gets created up to the moment it gets committed (median across validators).",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 155 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "quantile(0.5, histogram_quantile(0.5, sum by(job,le) (rate(certificate_commit_latency_bucket{job=~\"$validator\",network=\"$network\"}[5m]))))",
     "legendFormat": "p50"
    },
    {
     "expr": "quantile(0.5, histogram_quantile(0.95, sum by(job,le) (rate(certificate_commit_latency_bucket{job=~\"$validator\",network=\"$network\"}[5m]))))",
     "legendFormat": "p95"
    }
   ]
  },
  { "title": "DAG advancement", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 166 } },
  {
   "title": "Header to Certificate Latency",
   "type": "timeseries",
   "description": "Time it takes for a header to be materialized to a certificate (median across validators)",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 167 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "quantile(0.5, histogram_quantile(0.5, sum by(job,le) (rate(header_to_certificate_latency_bucket{job=~\"$validator\",network=\"$network\"}[5m]))))",
     "legendFormat": "p50"
    },
    {
     "expr": "quantile(0.5, histogram_quantile(0.95, sum by(job,le) (rate(header_to_certificate_latency_bucket{job=~\"$validator\",network=\"$network\"}[5m]))))",
     "legendFormat": "p95"
    }
   ]
  },
  {
   "title": "Round advancement latency",
   "type": "timeseries",
   "description": "Time it takes for a new proposal to be generated",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 167 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "quantile(0.5, histogram_quantile(0.5, sum by(job,le) (rate(proposal_latency_bucket{job=~\"$validator\",network=\"$network\"}[5m]))))",
     "legendFormat": "p50"
    },
    {
     "expr": "quantile(0.5, histogram_quantile(0.95, sum by(job,le) (rate(proposal_latency_bucket{job=~\"$validator\",network=\"$network\"}[5m]))))",
     "legendFormat": "p95"
    }
   ]
  },
  {
   "title": "Primary to Primary Latency by Route",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 167 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, route) (rate(primary_outbound_request_latency_bucket{job=~\"$validator\",network=\"$network\",route=~\".*PrimaryToPrimary.*\"}[5m])))",
     "legendFormat": "{{route}}-p95"
    }
   ]
  },
  {
   "title": "Suspended certificates by reason (avg across validators)",
   "type": "timeseries",
   "description": "Certificate is suspended until its parents are retrieved by the node. The dedup and dedup_locked correspond to the cases, in which the same certificate is received while being suspended.",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 178 },
   "targets": [
    {
     "expr": "avg by(reason) (rate(certificates_suspended{network=\"$network\", job=~\"$validator\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ratio of suspended to processed certificates",
   "type": "timeseries",
   "description": "Percentiles across validators\nThe value might be larger than 1 in case the same cert is suspended multiple times.",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 178 },
   "targets": [
    {
     "expr": "quantile(0.5,\nsum by (job) (rate(certificates_suspended{network=\"$network\", job=~\"$validator\"}[5m]))\n/\nsum by (job) (rate(certificates_processed{network=\"$network\", job=~\"$validator\"}[5m]))\n)",
     "legendFormat": "p50"
    },
    {
     "expr": "quantile(0.75,\nsum by (job) (rate(certificates_suspended{network=\"$network\", job=~\"$validator\"}[5m]))\n/\nsum by (job) (rate(certificates_processed{network=\"$network\", job=~\"$validator\"}[5m]))\n)",
     "legendFormat": "p75"
    },
    {
     "expr": "quantile(0.95,\nsum by (job) (rate(certificates_suspended{network=\"$network\", job=~\"$validator\"}[5m]))\n/\nsum by (job) (rate(certificates_processed{network=\"$network\", job=~\"$validator\"}[5m]))\n)",
     "legendFormat": "p95"
    }
   ]
  },
  {
   "title": "Worker to Worker Request Latency by Route",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 178 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, route) (rate(worker_outbound_request_latency_bucket{job=~\"$validator\",network=\"$network\", route=~\".*WorkerToWorker.*\"}[5m])))",
     "legendFormat": "{{route}}-p95"
    }
   ]
  },
  {
   "title": "Fetched certificates per sec for missing ancestors",
   "type": "timeseries",
   "description": "Counts all the processed fetched certificates, triggered by the missing parents.",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 189 },
   "targets": [
    {
     "expr": "quantile(0.5, rate(certificate_fetcher_num_certificates_processed{network=\"$network\", job=~\"$validator\"}[5m]))",
     "legendFormat": "p50"
    },
    {
     "expr": "quantile(0.75, rate(certificate_fetcher_num_certificates_processed{network=\"$network\", job=~\"$validator\"}[5m]))",
     "legendFormat": "p75"
    },
    {
     "expr": "quantile(0.95, rate(certificate_fetcher_num_certificates_processed{network=\"$network\", job=~\"$validator\"}[5m]))",
     "legendFormat": "p95"
    }
   ]
  },
  {
   "title": "Certificates processed (other)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 189 },
   "targets": [
    {
     "expr": "sum by (job) (rate(certificates_processed{job=~\"$validator\",network=\"$network\", source=\"other\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Fetch Certificates Response Size - p99",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 189 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(primary_inbound_response_size_bucket{network=~\"$network\", route=\"/narwhal.PrimaryToPrimary/FetchCertificates\", job=~\"$validator\"}[5m])) by (le, job))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Certificates processed (own)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 200 },
   "targets": [
    {
     "expr": "sum by (job) (rate(certificates_processed{job=~\"$validator\",network=\"$network\", source=\"own\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Outbound vs Inbound Latency Gap",
   "type": "timeseries",
   "description": "In case the delta between outbound and inbound latencies is high, it could be a sign of rate limiting or contention on the handler.",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 200 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(route) (rate(primary_outbound_request_latency_sum{job=~\"$validator\",network=\"$network\",route=~\".*PrimaryToPrimary.*\"}[5m])) / sum by(route) (rate(primary_outbound_request_latency_count{job=~\"$validator\",network=\"$network\",route=~\".*PrimaryToPrimary.*\"}[5m]))\n-\nsum by(route) (rate(primary_inbound_request_latency_sum{job=~\"$validator\",network=\"$network\",route=~\".*PrimaryToPrimary.*\"}[5m])) / sum by(route) (rate(primary_inbound_request_latency_count{job=~\"$validator\",network=\"$network\",route=~\".*PrimaryToPrimary.*\"}[5m]))",
     "legendFormat": "{{route}}"
    },
    {
     "expr": "sum by(route) (rate(worker_outbound_request_latency_sum{host=~\"$validator\",network=\"$network\", route=~\".*WorkerToWorker.*\"}[5m])) / sum by(route) (rate(worker_outbound_request_latency_count{host=~\"$validator\",network=\"$network\", route=~\".*WorkerToWorker.*\"}[5m]))\n-\nsum by(route) (rate(worker_inbound_request_latency_sum{host=~\"$validator\",network=\"$network\", route=~\".*WorkerToWorker.*\"}[5m])) / sum by(route) (rate(worker_inbound_request_latency_count{host=~\"$validator\",network=\"$network\", route=~\".*WorkerToWorker.*\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Anemo rps per validator",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 200 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "quantile(0.5, sum by(job) (rate(primary_outbound_request_latency_count{job=~\"$validator\",network=\"$network\"}[5m])))",
     "legendFormat": "primary_outbound"
    },
    {
     "expr": "quantile(0.5, sum by(job) (rate(worker_outbound_request_latency_count{job=~\"$validator\",network=\"$network\"}[5m])))\n",
     "legendFormat": "worker_outbound"
    },
    {
     "expr": "quantile(0.5, sum by(job) (rate(primary_inbound_request_latency_count{job=~\"$validator\",network=\"$network\"}[5m])))",
     "legendFormat": "primary_inbound"
    },
    {
     "expr": "quantile(0.5, sum by(job) (rate(worker_inbound_request_latency_count{job=~\"$validator\",network=\"$network\"}[5m])))",
     "legendFormat": "worker_inbound"
    }
   ]
  },
  { "title": "Executor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 211 } },
  {
   "title": "Certificate to Subscriber Latency",
   "type": "timeseries",
   "description": "Time between cert creation and the moment it has reached the executor (median across validators).",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 212 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "quantile(0.5, histogram_quantile(0.5, sum by(job,le) (rate(subscriber_certificate_latency_bucket{job=~\"$validator\",network=\"$network\"}[5m]))))",
     "legendFormat": "p50"
    },
    {
     "expr": "quantile(0.5, histogram_quantile(0.95, sum by(job,le) (rate(subscriber_certificate_latency_bucket{job=~\"$validator\",network=\"$network\"}[5m]))))",
     "legendFormat": "p95"
    }
   ]
  },
  {
   "title": "Batch to Execution Latency",
   "type": "timeseries",
   "description": "Latency between the time when the batch has been created and the moment it has been fetched for execution (median across validators)",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 212 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "quantile(0.5, histogram_quantile(0.5, sum by(job,le) (rate(batch_execution_latency_bucket{job=~\"$validator\",network=\"$network\"}[5m]))))",
     "legendFormat": "p50"
    },
    {
     "expr": "quantile(0.5, histogram_quantile(0.95, sum by(job,le) (rate(batch_execution_latency_bucket{job=~\"$validator\",network=\"$network\"}[5m]))))",
     "legendFormat": "p95"
    }
   ]
  },
  { "title": "NW Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 223 } },
  {
   "title": "Worker network connectivity",
   "type": "timeseries",
   "description": "Num of primary peers connected per host",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 224 },
   "targets": [
    {
     "expr": "sum by (job) (worker_network_peer_connected{job=~\"$validator\", network=\"$network\", type=\"other_worker\"})",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Congestion Events ",
   "type": "timeseries",
   "description": "Congestion events for primary and worker connections",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 224 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(job) (rate(worker_network_peer_congestion_events{job=~\"$validator\", network=\"$network\"}[5m]))",
     "legendFormat": "worker-{{host}}"
    },
    {
     "expr": "sum by(job) (rate(primary_network_peer_congestion_events{job=~\"$validator\", network=\"$network\"}[5m]))",
     "legendFormat": "primary-{{host}}"
    }
   ]
  },
  {
   "title": "Packet Loss %",
   "type": "timeseries",
   "description": "Packet loss for primary and worker connections",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 224 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by(job) (rate(worker_network_peer_lost_packets{job=~\"$validator\", network=\"$network\"}[5m])) / sum by(job) (rate(worker_network_peer_sent_packets{job=~\"$validator\", network=\"$network\"}[5m])) * 100",
     "legendFormat": "worker-{{host}}"
    },
    {
     "expr": "sum by(job) (rate(primary_network_peer_lost_packets{job=~\"$validator\", network=\"$network\"}[5m])) / sum by(job) (rate(primary_network_peer_sent_packets{job=~\"$validator\", network=\"$network\"}[5m])) * 100",
     "legendFormat": "primary-{{host}}"
    }
   ]
  }
 ]
}