processed 1 task

task 0, lines 6-16:
//# publish
Error: Transaction Effects Status: Ika Move Bytecode Verification Error. Please run the Ika Move Verifier for more information.
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: IkaMoveVerificationError, source: Some("Expected last (and at most second) parameter for _::m::init to be &mut ika::tx_context::TxContext or &ika::tx_context::TxContext; optional first parameter must be of one-time witness type whose name is the same as the capitalized module name (_::m::M) and which has no fields or a single field of type bool"), command: Some(0) } }
