[package]
name = "pera-genesis-builder"
version = "0.0.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "BSD-3-Clause-Clear"
publish = false
edition = "2021"

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
bcs.workspace = true
camino.workspace = true
fastcrypto.workspace = true
move-binary-format.workspace = true
move-core-types.workspace = true
rand.workspace = true
serde.workspace = true
serde_with.workspace = true
serde_yaml.workspace = true
tempfile.workspace = true
tracing.workspace = true
prometheus.workspace = true

shared-crypto.workspace = true
pera-config.workspace = true
pera-execution.workspace = true
pera-framework.workspace = true
pera-framework-snapshot.workspace = true
pera-protocol-config.workspace = true
pera-types.workspace = true
dwallet-classgroups-types.workspace = true
[target.'cfg(msim)'.dependencies]
pera-simulator.workspace = true

[dev-dependencies]
insta.workspace = true
tempfile.workspace = true
pera-types = { workspace = true, features = ["test-utils"] }
