[package]
name = "pera-adapter-latest"
version = "0.1.0"
authors = ["Mysten Labs <eng@mystenlabs.com>"]
description = "Adapter and accompanying CLI for local pera development"
license = "BSD-3-Clause-Clear"
publish = false
edition = "2021"

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true, features = ["backtrace"] }
bcs.workspace = true
leb128.workspace = true
tracing.workspace = true
serde.workspace = true
dwallet-mpc-types.workspace = true

move-binary-format.workspace = true
move-bytecode-utils.workspace = true
move-bytecode-verifier-meter.workspace = true
move-core-types.workspace = true
move-vm-config.workspace = true
move-vm-types.workspace = true
mysten-metrics.workspace = true

move-bytecode-verifier = { path = "../../../external-crates/move/crates/move-bytecode-verifier" }
move-vm-runtime = { path = "../../../external-crates/move/crates/move-vm-runtime" }
move-vm-profiler = { path = "../../../external-crates/move/crates/move-vm-profiler" }
pera-move-natives = { path = "../pera-move-natives", package = "pera-move-natives-latest" }
pera-verifier = { path = "../pera-verifier", package = "pera-verifier-latest" }

pera-macros.workspace = true
pera-protocol-config.workspace = true
pera-types.workspace = true
parking_lot.workspace = true

[dev-dependencies]
move-package.workspace = true

[features]
gas-profiler = [
    "pera-types/gas-profiler",
    "move-vm-runtime/gas-profiler",
    "move-vm-profiler/gas-profiler",
    "move-vm-types/gas-profiler",
    "move-vm-config/gas-profiler",
]
