---
version: "3.9"
services:
  fullnode:
    image: 471930101563.dkr.ecr.us-east-1.amazonaws.com/sui-fork:dwallet
    ports:
    - "8084:8084/udp"
    - "9000:9000"
    - "9184:9184"
    volumes:
    - ./fullnode-template.yaml:/opt/sui/config/fullnode.yaml:ro
    - ./genesis.blob:/opt/sui/config/genesis.blob:ro
    - suidb:/opt/sui/db:rw
    command: ["/opt/sui/bin/sui-node", "--config-path", "/opt/sui/config/fullnode.yaml"]
volumes:
  suidb:
