---
version: "3"

services:
  validator:
    container_name: validator
    image: 471930101563.dkr.ecr.us-east-1.amazonaws.com/sui-fork:dwallet # UPDATE HERE
    environment:
      - RUST_BACKTRACE=1
      - RUST_LOG=info,sui_core=debug,narwhal=debug,narwhal-primary::helper=info,jsonrpsee=error
    labels:
      org.label-schema.name: "validator"
    ports:
      - "8080:8080"
      - "8081:8081/udp"
      - "8082:8082/udp"
      - "8084:8084/udp"
      - "9184:9184"
    network_mode: "host"
    volumes:
      - ./validator.yaml:/opt/sui/config/validator.yaml:ro
      - ./genesis.blob:/opt/sui/config/genesis.blob:ro
      - ./key-pairs:/opt/sui/key-pairs/:ro
      - /opt/sui/db:/opt/sui/db:rw
    command:
      [
        "/opt/sui/bin/sui-node",
        "--config-path",
        "/opt/sui/config/validator.yaml",
      ]
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "5g"
