error[Pera E02007]: invalid object declaration
  ┌─ tests/pera_mode/struct_with_key/key_struct_second_field_id.move:6:9
  │
5 │     struct S has key {
  │                  --- The 'key' ability is used to declare objects in Pera
6 │         flag: bool,
  │         ^^^^ Invalid object 'S'. Structs with the 'key' ability must have 'id: pera::object::UID' as their first field

error[Pera E02007]: invalid object declaration
   ┌─ tests/pera_mode/struct_with_key/key_struct_second_field_id.move:11:9
   │
10 │     struct R has key {
   │                  --- The 'key' ability is used to declare objects in Pera
11 │         flag: bool,
   │         ^^^^ Invalid object 'R'. Structs with the 'key' ability must have 'id: pera::object::UID' as their first field

