[package]
name = "sui-rest-api"
version = "0.1.0"
edition = "2021"
license = "BSD-3-Clause-Clear"
publish = false

[dependencies]
anyhow.workspace = true
serde.workspace = true
bcs.workspace = true
reqwest.workspace = true
axum.workspace = true
rand.workspace = true
simulacrum.workspace = true
sui-types.workspace = true
sui-core.workspace = true
workspace-hack.workspace = true

[dev-dependencies]
tokio.workspace = true
