error[Ika E02003]: invalid 'init' function
  ┌─ tests/ika_mode/init/must_have_txn_context.move:3:9
  │
3 │     fun init() {
  │         ^^^^
  │         │
  │         Invalid 'init' function declaration
  │         'init' functions must have their last parameter as '&ika::tx_context::TxContext' or '&mut ika::tx_context::TxContext'

error[Ika E02003]: invalid 'init' function
   ┌─ tests/ika_mode/init/must_have_txn_context.move:11:9
   │
11 │     fun init(_ctx: &mut tx_context::TxContext, _ctx2: &mut tx_context::TxContext) {
   │         ^^^^       -------------------------- Invalid parameter '_ctx' of type '&mut ika::tx_context::TxContext'. Expected a one-time witness type, 'a::n::N
   │         │           
   │         Invalid 'init' function declaration
   │
   = One-time witness types are structs with the following requirements: their name is the upper-case version of the module's name, they have no fields (or a single boolean field), they have no type parameters, and they have only the 'drop' ability.

