error[Ika E02002]: invalid 'entry' function signature
  ┌─ tests/ika_mode/entry_points/clock_mut.move:4:35
  │
4 │     public entry fun no_clock_mut(_: &mut ika::clock::Clock) {
  │            -----                  ^  ---------------------- ika::clock::Clock must be passed by immutable reference, e.g. '&ika::clock::Clock'
  │            │                      │   
  │            │                      Invalid 'entry' parameter type for parameter '_'
  │            'no_clock_mut' was declared 'entry' here

