[package]
name = "pera-rest-api"
version = "0.1.0"
edition = "2021"
license = "BSD-3-Clause-Clear"
publish = false

[dependencies]
mime = "0.3.17"
anyhow.workspace = true
axum = { workspace = true, features = ["matched-path"] }
bcs.workspace = true
rand.workspace = true
reqwest.workspace = true
url.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
serde_with.workspace = true
tap.workspace = true
thiserror.workspace = true
tokio.workspace = true
async-trait.workspace = true
itertools.workspace = true
pera-sdk2.workspace = true
prometheus.workspace = true
openapiv3 = { git = "https://github.com/bmwill/openapiv3.git", rev = "ca4b4845b7c159a39f5c68ad8f7f76cb6f4d6963" }
schemars.workspace = true
dwallet-mpc-types.workspace = true

fastcrypto.workspace = true
pera-types.workspace = true
mysten-network.workspace = true
pera-protocol-config.workspace = true

[dev-dependencies]
diffy = "0.3"
