[package]
name = "sui-graphql-rpc"
version = "0.1.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "BSD-3-Clause-Clear"
publish = false
edition = "2021"


[dependencies]
anyhow.workspace = true
async-graphql = {workspace = true, features = ["dataloader", "apollo_tracing", "tracing", "opentelemetry"] }
async-graphql-axum.workspace = true
async-trait.workspace = true
axum.workspace = true
chrono.workspace = true
clap.workspace = true
diesel.workspace = true
either.workspace = true
fastcrypto = { workspace = true, features = ["copy_key"] }
futures.workspace = true
hex.workspace = true
http.workspace = true
hyper.workspace = true
lru.workspace = true
move-binary-format.workspace = true
move-disassembler.workspace = true
move-ir-types.workspace = true
markdown-gen.workspace = true
mysten-metrics.workspace = true
move-core-types.workspace = true
once_cell.workspace = true
prometheus.workspace = true
rand.workspace = true # todo: cleanup test only deps
regex.workspace = true
reqwest.workspace = true
serial_test.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_with.workspace = true
serde_yaml.workspace = true
shared-crypto.workspace = true
similar.workspace = true
sui-sdk.workspace = true
sui-types.workspace = true
tap.workspace = true
telemetry-subscribers.workspace = true
tracing.workspace = true
tokio.workspace = true
toml.workspace = true
tower.workspace = true
thiserror.workspace = true
uuid.workspace = true

sui-graphql-rpc-headers.workspace = true
sui-graphql-rpc-client.workspace = true


# TODO: put these behind feature flag to prevent leakage
# Used for dummy data
bcs.workspace = true
simulacrum.workspace = true  # todo: cleanup test only deps
sui-json-rpc.workspace = true
sui-json-rpc-types.workspace = true
sui-indexer.workspace = true
sui-rest-api.workspace = true
sui-swarm-config.workspace = true
test-cluster.workspace = true
sui-protocol-config.workspace = true
move-bytecode-utils.workspace = true
workspace-hack.workspace = true
sui-package-resolver.workspace = true

[dev-dependencies]
expect-test.workspace = true
hyper.workspace = true
insta.workspace = true
serde_json.workspace = true
sui-framework.workspace = true
tower.workspace = true

[features]
default = ["pg_backend"]
pg_integration = []
pg_backend = []
