[package]
name = "move-vm-profiler"
version = "0.1.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "BSD-3-Clause-Clear"
publish = false
edition = "2021"

[dependencies]
serde.workspace = true
serde_json.workspace = true
once_cell.workspace = true

move-vm-config.workspace = true
