error[Ika E02007]: invalid object declaration
  ┌─ tests/ika_mode/struct_with_key/key_struct_id_field_incorrect_type.move:4:9
  │
3 │     struct S has key {
  │                  --- The 'key' ability is used to declare objects in Ika
4 │         id: bool
  │         ^^  ---- But found type: 'bool'
  │         │    
  │         Invalid object 'S'. Structs with the 'key' ability must have 'id: ika::object::UID' as their first field

