[package]
name = "ika-move-packages"
version = "0.1.0"
edition = "2021"
authors = ["dWallet Labs Ltd. <dev@dwalletlabs.com>"]
description = "Sui Move packages"
license = "BSD-3-Clause-Clear"
publish = false

[dependencies]
bcs.workspace = true
serde.workspace = true
once_cell.workspace = true
tracing.workspace = true

sui-types.workspace = true
sui-protocol-config.workspace = true

move-binary-format.workspace = true
anyhow.workspace = true

[dev-dependencies]
anyhow.workspace = true
bcs.workspace = true
regex.workspace = true
tempfile.workspace = true

move-binary-format.workspace = true
move-compiler.workspace = true
move-package.workspace = true
sui-move-build.workspace = true
