processed 1 task

task 0, lines 4-13:
//# publish
Error: Transaction Effects Status: Pera Move Bytecode Verification Error. Please run the Pera Move Verifier for more information.
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: PeraMoveVerificationError, source: Some("Invalid entry point parameter type. Expected primitive or object type. Got: vector<vector<T0>>"), command: Some(0) } }
