[package]
name = "sui-telemetry"
version = "0.1.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "BSD-3-Clause-Clear"
publish = false
edition = "2021"

[dependencies]
serde.workspace = true
reqwest.workspace = true
tracing.workspace = true

sui-core.workspace = true
workspace-hack.workspace = true

