"use strict";
// Copyright (c) dWallet Labs, Ltd.
// SPDX-License-Identifier: BSD-3-Clause-Clear
Object.defineProperty(exports, "__esModule", { value: true });
exports.TARGETED_RPC_VERSION = exports.PACKAGE_VERSION = void 0;
// This file is generated by genversion.mjs. Do not edit it directly.
exports.PACKAGE_VERSION = '0.49.20';
exports.TARGETED_RPC_VERSION = '1.16.2';
//# sourceMappingURL=version.js.map