// Copyright (c) dWallet Labs, Ltd.
// SPDX-License-Identifier: BSD-3-Clause-Clear

// This file is generated by genversion.mjs. Do not edit it directly.

export const PACKAGE_VERSION = '0.49.20';
export const TARGETED_RPC_VERSION = '1.16.2';
