[package]
name = "pera-mpc-types"
version.workspace = true
edition = "2021"
authors = ["Mysten Labs <eng@mystenlabs.com>"]
description = "MPC types for Pera"
license = "BSD-3-Clause-Clear"
publish = false

[dependencies]
move-core-types.workspace = true
thiserror.workspace = true
bcs.workspace = true
twopc_mpc.workspace = true

[dev-dependencies]
