[package]
name = "sui-archival"
version = "0.1.0"
edition = "2021"
publish = false
license = "BSD-3-Clause-Clear"
authors = ["Mysten Labs <build@mystenlabs.com>"]

[dependencies]
indicatif.workspace = true
anyhow.workspace = true
serde.workspace = true
byteorder.workspace = true
tracing.workspace = true
bytes.workspace = true
num_enum.workspace = true
futures.workspace = true
rand.workspace = true
object_store.workspace = true
prometheus.workspace = true
sui-config.workspace = true
sui-types.workspace = true
sui-storage.workspace = true
fastcrypto = { workspace = true, features = ["copy_key"] }
tokio = { workspace = true, features = ["full"] }
workspace-hack.workspace = true

[dev-dependencies]
tempfile.workspace = true
more-asserts.workspace = true
telemetry-subscribers.workspace = true
move-binary-format.workspace = true
move-core-types.workspace = true
move-package.workspace = true
tokio = { workspace = true, features = ["test-util"] }
ed25519-consensus.workspace = true
fastcrypto = { workspace = true }
sui-swarm-config.workspace = true
sui-macros.workspace = true

[target.'cfg(msim)'.dependencies]
sui-simulator.workspace = true
