[package]
name = "sui-move-natives-v1"
version = "0.1.0"
edition = "2021"
authors = ["Mysten Labs <eng@mystenlabs.com>"]
description = "Move framework for sui platform"
license = "BSD-3-Clause-Clear"
publish = false

[dependencies]
better_any.workspace = true
bcs.workspace = true
linked-hash-map = "0.5.6"
smallvec.workspace = true

fastcrypto-zkp.workspace = true
fastcrypto.workspace = true
move-binary-format.workspace = true
move-core-types.workspace = true
move-vm-types.workspace = true

move-stdlib = { path = "../../../external-crates/move/move-execution/v1/crates/move-stdlib", package = "move-stdlib-v1" }
move-vm-runtime = { path = "../../../external-crates/move/move-execution/v1/crates/move-vm-runtime", package = "move-vm-runtime-v1" }

sui-protocol-config.workspace = true
sui-types.workspace = true
workspace-hack.workspace = true
tracing.workspace = true
