processed 4 tasks

task 0, lines 6-16:
//# publish
Error: Transaction Effects Status: Ika Move Bytecode Verification Error. Please run the Ika Move Verifier for more information.
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: IkaMoveVerificationError, source: Some("_::m::t. Invalid call to 'ika::transfer::transfer' on an object of type 'ika::coin::Coin<u64>'. The transferred object's type must be defined in the current module. If the object has the 'store' type ability, you can use the non-internal variant instead, i.e. 'ika::transfer::public_transfer'"), command: Some(0) } }

task 1, lines 18-28:
//# publish
Error: Transaction Effects Status: Ika Move Bytecode Verification Error. Please run the Ika Move Verifier for more information.
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: IkaMoveVerificationError, source: Some("_::m::t. Invalid call to 'ika::transfer::freeze_object' on an object of type 'ika::coin::Coin<u64>'. The transferred object's type must be defined in the current module. If the object has the 'store' type ability, you can use the non-internal variant instead, i.e. 'ika::transfer::public_freeze_object'"), command: Some(0) } }

task 2, lines 30-40:
//# publish
Error: Transaction Effects Status: Ika Move Bytecode Verification Error. Please run the Ika Move Verifier for more information.
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: IkaMoveVerificationError, source: Some("_::m::t. Invalid call to 'ika::transfer::share_object' on an object of type 'ika::coin::Coin<u64>'. The transferred object's type must be defined in the current module. If the object has the 'store' type ability, you can use the non-internal variant instead, i.e. 'ika::transfer::public_share_object'"), command: Some(0) } }

task 3, lines 42-54:
//# publish
Error: Transaction Effects Status: Ika Move Bytecode Verification Error. Please run the Ika Move Verifier for more information.
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: IkaMoveVerificationError, source: Some("_::m::t. Invalid call to 'ika::transfer::receive' on an object of type 'ika::coin::Coin<u64>'. The transferred object's type must be defined in the current module. If the object has the 'store' type ability, you can use the non-internal variant instead, i.e. 'ika::transfer::public_receive'"), command: Some(0) } }
