processed 3 tasks

task 1, lines 6-9:
//# publish --upgradeable
created: object(1,0), object(1,1)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 5532800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, line 11:
//# view-object 1,1
Owner: Account Address ( _ )
Version: 2
Contents: pera::package::UpgradeCap {
    id: pera::object::UID {
        id: pera::object::ID {
            bytes: fake(1,1),
        },
    },
    package: pera::object::ID {
        bytes: Test,
    },
    version: 1u64,
    policy: 0u8,
}
