[package]
name = "sui-execution-cut"
version = "0.1.0"
edition = "2021"
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "BSD-3-Clause-Clear"
publish = false

[dependencies]
anyhow.workspace = true
clap = { version = "4.3.1", features = ["derive"] }
thiserror.workspace = true
toml.workspace = true
toml_edit.workspace = true
workspace-hack.workspace = true

[dev-dependencies]
expect-test.workspace = true
tempfile.workspace = true

[[bin]]
name = "cut"
path = "src/main.rs"
