[package]
name = "DeepBook"
version = "0.0.1"
published-at = "0xdee9"

[dependencies]
MoveStdlib = { local = "../move-stdlib" }
dWallet = { local = "../dwallet-framework" }

[addresses]
deepbook = "0xdee9"
