[package]
name = "Locked Stake"
version = "0.0.1"

[dependencies]
dWallet = { local = "../../../crates/sui-framework/packages/dwallet-framework" }
DWalletSystem = { local = "../../../crates/sui-framework/packages/dwallet-system" }

[addresses]
locked_stake = "0x0"
