[package]
name = "sui-json-rpc"
version = "0.0.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "BSD-3-Clause-Clear"
publish = false
edition = "2021"

[dependencies]
arc-swap.workspace = true
fastcrypto.workspace = true
jsonrpsee.workspace = true
hyper.workspace = true
itertools.workspace = true
indexmap.workspace = true
tower.workspace = true
axum.workspace = true
tower-http.workspace = true
move-binary-format.workspace = true
move-core-types.workspace = true
move-package.workspace = true
move-bytecode-utils.workspace = true
prometheus.workspace = true
anyhow.workspace = true
tracing.workspace = true
async-trait.workspace = true
serde.workspace = true
futures.workspace = true
tokio = { workspace = true, features = ["full"] }
signature.workspace = true
thiserror.workspace = true
bcs.workspace = true
eyre.workspace = true
once_cell.workspace = true
serde_json.workspace = true

tap.workspace = true

sui-core.workspace = true
sui-storage.workspace = true
sui-types.workspace = true
sui-json.workspace = true
sui-json-rpc-api.workspace = true
sui-open-rpc.workspace = true
sui-open-rpc-macros.workspace = true
sui-protocol-config.workspace = true
sui-json-rpc-types.workspace = true
sui-transaction-builder.workspace = true
mysten-metrics.workspace = true
shared-crypto.workspace = true
typed-store-error.workspace = true
cached.workspace = true
workspace-hack.workspace = true

[dev-dependencies]
mockall.workspace = true
expect-test.workspace = true
sui-types = { workspace = true, features = ["test-utils"] }
telemetry-subscribers.workspace = true
