[package]
name = "sui-adapter-transactional-tests"
version = "0.1.0"
authors = ["Mysten Labs <eng@mystenlabs.com>"]
description = "Transactional tests for Sui Adapter"
license = "BSD-3-Clause-Clear"
publish = false
edition = "2021"

[dev-dependencies]
datatest-stable.workspace = true
sui-transactional-test-runner.workspace = true

[[test]]
name = "tests"
harness = false

[dependencies]
workspace-hack.workspace = true
