[package]
name = "mysten-util-mem-derive"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
license = "BSD-3-Clause-Clear"
description = "Crate for memory reporting"
repository = "https://github.com/mystenlabs/mysten-infra"
edition = "2021"
rust-version = "1.56.1"
publish = false

[lib]
path = "lib.rs"
proc-macro = true

[dependencies]
proc-macro2.workspace = true
syn.workspace = true
synstructure.workspace = true
workspace-hack.workspace = true
