[package]
name = "sui-adapter-latest"
version = "0.1.0"
authors = ["Mysten Labs <eng@mystenlabs.com>"]
description = "Adapter and accompanying CLI for local sui development"
license = "BSD-3-Clause-Clear"
publish = false
edition = "2021"

[dependencies]
anyhow = { workspace = true, features = ["backtrace"] }
bcs.workspace = true
leb128.workspace = true
tracing.workspace = true
serde.workspace = true

move-binary-format.workspace = true
move-bytecode-utils.workspace = true
move-core-types.workspace = true
move-vm-config.workspace = true
move-vm-types.workspace = true

move-bytecode-verifier = { path = "../../../external-crates/move/crates/move-bytecode-verifier" }
move-vm-runtime = { path = "../../../external-crates/move/crates/move-vm-runtime" }
move-vm-profiler = { path = "../../../external-crates/move/crates/move-vm-profiler" }
sui-move-natives = { path = "../sui-move-natives", package = "sui-move-natives-latest" }
sui-verifier = { path = "../sui-verifier", package = "sui-verifier-latest" }

sui-macros.workspace = true
sui-protocol-config.workspace = true
sui-types.workspace = true
parking_lot.workspace = true
workspace-hack.workspace = true

[dev-dependencies]
move-package.workspace = true
