[package]
name = "move-errmapgen"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
publish = false
edition = "2021"
license = "BSD-3-Clause-Clear"

[dependencies]
# Move dependencies
move-command-line-common.workspace = true
move-model.workspace = true
move-core-types.workspace = true

# external dependencies
anyhow.workspace = true
serde.workspace = true

[dev-dependencies]
codespan-reporting.workspace = true
move-prover.workspace = true
datatest-stable.workspace = true
