[package]
name = "move-vm-config"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
repository = "https://github.com/move-language/move"
license = "BSD-3-Clause-Clear"
publish = false
edition = "2021"

[dependencies]
move-binary-format.workspace = true
