[package]
name = "move-explain"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
description = "Explain Move abort codes. Errors are defined as a global category + module-specific reason for the error"
repository = "https://github.com/diem/diem"
homepage = "https://diem.com"
license = "BSD-3-Clause-Clear"
publish = false
edition = "2021"

[dependencies]
clap.workspace = true
move-command-line-common.workspace = true
move-core-types.workspace = true

bcs.workspace = true

[features]
default = []
