[package]
name = "dWallet"
version = "0.0.1"
published-at = "0x2"

[dependencies]
# Using a local dep for the Move stdlib instead of a git dep to avoid the overhead of fetching the git dep in
# CI. The local dep is an unmodified version of the upstream stdlib
MoveStdlib = { local = "../move-stdlib" }
#MoveStdlib = { git = "https://github.com/diem/diem.git", subdir="language/move-stdlib", rev = "346301f33b3489bb4e486ae6c0aa5e030223b492" }

[addresses]
dwallet = "0x2"
