# https://grafana.com/docs/mimir/latest/references/architecture/components/overrides-exporter/
target: all,alertmanager

server:
  http_listen_port: 9009
  log_level: warn

blocks_storage:
  backend: filesystem
  filesystem:
    dir: /tmp/mimir/tsdb

compactor:
  data_dir: /tmp/mimir/compactor

alertmanager_storage:
  backend: filesystem
  filesystem:
    dir: /tmp/mimir/alerts

ingester:
  ring:
    kvstore:
      store: inmemory
    replication_factor: 1

multitenancy_enabled: false
