processed 2 tasks

task 0, lines 4-26:
//# publish
Error: Transaction Effects Status: Ika Move Bytecode Verification Error. Please run the Ika Move Verifier for more information.
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: IkaMoveVerificationError, source: Some("PartialVMError with status UNKNOWN_VERIFICATION_ERROR with sub status 1 and message Invalid object creation in _::m::foo. Object created without a newly created UID. The UID must come directly from ika::object::new. Or for tests, it can come from ika::test_scenario::new_object"), command: Some(0) } }

task 1, lines 28-50:
//# publish
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 4590400,  storage_rebate: 978120, non_refundable_storage_fee: 9880
