processed 3 tasks

task 0, lines 4-11:
//# publish
Error: Transaction Effects Status: Ika Move Bytecode Verification Error. Please run the Ika Move Verifier for more information.
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: IkaMoveVerificationError, source: Some("Expected last parameter for _::m::init to be &mut ika::tx_context::TxContext or &ika::tx_context::TxContext, but found u64"), command: Some(0) } }

task 1, lines 13-20:
//# publish
Error: Transaction Effects Status: Ika Move Bytecode Verification Error. Please run the Ika Move Verifier for more information.
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: IkaMoveVerificationError, source: Some("Expected last parameter for _::tx_context::init to be &mut ika::tx_context::TxContext or &ika::tx_context::TxContext, but found _::tx_context::TxContext"), command: Some(0) } }

task 2, lines 22-29:
//# publish
Error: Transaction Effects Status: Ika Move Bytecode Verification Error. Please run the Ika Move Verifier for more information.
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: IkaMoveVerificationError, source: Some("Expected last parameter for _::m::init to be &mut ika::tx_context::TxContext or &ika::tx_context::TxContext, but found ika::tx_context::TxContext"), command: Some(0) } }
