// Copyright (c) dWallet Labs, Inc.
// SPDX-License-Identifier: BSD-3-Clause-Clear

import path from 'path';
import { encrypt_secret_share } from '@dwallet-network/dwallet-mpc-wasm';
import { getFullnodeUrl, SuiClient } from '@mysten/sui/client';
import { getFaucetHost, requestSuiFromFaucetV1 } from '@mysten/sui/faucet';
import { Ed25519Keypair } from '@mysten/sui/keypairs/ed25519';
import { beforeEach, describe, it } from 'vitest';

import {
	createDKGFirstRoundOutputMock,
	createDWallet,
	dkgSecondRoundMoveCall,
} from '../../src/dwallet-mpc/dkg';
import { getOrCreateClassGroupsKeyPair } from '../../src/dwallet-mpc/encrypt-user-share';
import {
	checkpointCreationTime,
	Config,
	delay,
	getDWalletSecpState,
	mockedProtocolPublicParameters,
} from '../../src/dwallet-mpc/globals';
import { presign } from '../../src/dwallet-mpc/presign';
import { dkgFirstRoundMock } from './mocks';

const fiveMinutes = 5 * 60 * 1000;
describe('Test dWallet MPC', () => {
	let conf: Config;

	beforeEach(async () => {
		const keypair = Ed25519Keypair.deriveKeypairFromSeed('0x1');
		const dWalletSeed = new Uint8Array(32).fill(8);
		const encryptedSecretShareSigningKeypair = Ed25519Keypair.deriveKeypairFromSeed(
			Buffer.from(dWalletSeed).toString('hex'),
		);
		const address = keypair.getPublicKey().toSuiAddress();
		const suiClient = new SuiClient({ url: getFullnodeUrl('localnet') });
		await requestSuiFromFaucetV1({
			host: getFaucetHost('localnet'),
			recipient: address,
		});

		conf = {
			suiClientKeypair: keypair,
			client: suiClient,
			timeout: fiveMinutes,
			ikaConfig: require(path.resolve(process.cwd(), '../../ika_config.json')),
			dWalletSeed,
			encryptedSecretShareSigningKeypair,
		};
		await delay(2000);
	});

	it('should create a dWallet (DKG)', async () => {
		await createDWallet(conf, mockedProtocolPublicParameters);
	});

	it('should run the DKG second round', async () => {
		let classGroupsKeypair = await getOrCreateClassGroupsKeyPair(conf);
		await delay(checkpointCreationTime);

		const dwalletState = await getDWalletSecpState(conf);
		const firstRoundOutputResult = await createDKGFirstRoundOutputMock(
			conf,
			Buffer.from(dkgFirstRoundMock.firstRoundOutput, 'base64'),
		);
		await delay(checkpointCreationTime);
		let encryptedSecretShare = encrypt_secret_share(
			Buffer.from(dkgFirstRoundMock.centralizedSecretKeyShare, 'base64'),
			classGroupsKeypair.encryptionKey,
		);
		await dkgSecondRoundMoveCall(
			conf,
			dwalletState,
			{
				sessionID: dkgFirstRoundMock.sessionID,
				dwalletCapID: firstRoundOutputResult.dwalletCapID,
				output: Buffer.from(dkgFirstRoundMock.firstRoundOutput, 'base64'),
				dwalletID: firstRoundOutputResult.dwalletID,
			},
			Buffer.from(dkgFirstRoundMock.centralizedPublicKeyShareAndProof, 'base64'),
			encryptedSecretShare,
			Buffer.from(dkgFirstRoundMock.centralizedPublicOutput, 'base64'),
		);
		console.log(`dWallet has been created successfully: ${firstRoundOutputResult.dwalletID}`);
	});

	it('should run presign', async () => {
		await getOrCreateClassGroupsKeyPair(conf);
		await delay(checkpointCreationTime);

		const dwalletState = await getDWalletSecpState(conf);
		const firstRoundOutputResult = await createDKGFirstRoundOutputMock(
			conf,
			Buffer.from(dkgFirstRoundMock.firstRoundOutput, 'base64'),
		);
		await delay(checkpointCreationTime);
		await dkgSecondRoundMoveCall(
			conf,
			dwalletState,
			{
				sessionID: dkgFirstRoundMock.sessionID,
				dwalletCapID: firstRoundOutputResult.dwalletCapID,
				output: Buffer.from(dkgFirstRoundMock.firstRoundOutput, 'base64'),
				dwalletID: firstRoundOutputResult.dwalletID,
			},
			Buffer.from(dkgFirstRoundMock.centralizedPublicKeyShareAndProof, 'base64'),
			Buffer.from(dkgFirstRoundMock.encryptedSecretShareAndProof, 'base64'),
			Buffer.from(dkgFirstRoundMock.centralizedPublicOutput, 'base64'),
		);
		console.log(`dWallet has been created successfully: ${firstRoundOutputResult.dwalletID}`);
		const presignCompletion = await presign(conf, firstRoundOutputResult.dwalletID);
		console.log(`presign has been created successfully: ${presignCompletion.presign_id}`);
	});
});

describe('DWallet tests - offline', () => {
	it('should encrypt a secret share', () => {
		let encryptionKey = Buffer.from(
			'OlRoZSBmaW5pdGUgZmllbGQgb2YgaW50ZWdlcnMgbW9kdWxvIHByaW1lIHEgJFxtYXRoYmJ7Wn1fcSQgQUE20Ixe0r87oEiv5tyuuv7///////////////////8gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEABgAA6wIAAGwEAACAAg0Y7Dps2OpqvRzwqAJMv2JLAdXl/cc5QyVxiC+y+rJ/hNyP1zV10zIFULSTjeFLREhRel+sZxnQ+3gLwDXdi2EmGHRfO4cBdOZufGD7ZP879v72QQksmWL8MsfUsBjp3a79nJMJ2hCD07af7AVflj6NwXe9gTZK3jDylZDg1pmKFBWiIMobvoH278MFoSKcwZym0ve62RjDsuBX0irmYsXXHj0UFYzm6go95cq5L4OYNYu4bxEKcq42klrrt/HzHOrCn5ZQ2DPH0fqUaame/URYtqagPYQnPPCwA58oLtAM453kxmnZD8vy//////////////////////////////8CAAAAAAAAAMABjWe6QLn0pkvVoIYzefP42KAfC8AvBJS97sytrZlZqDfV3iEje439xU9k97J1rh9TBOjyI/YPgzaj+1H3el9V4pSBwqLdhroXWDy5bn4gEM2CMMvcADAFeXcd4YzrUVRw7noI7rZcGyb/hH/ZcgFyoM5H7ZmBdDtMEY6dDPR1PyoCyHxV7A0dYDFuRdJfjAQP88UgczWjXqvOsAOfKC7QDOOd5MZp2Q/L8v//////////////////////////////gAINGOw6bNjqar0c8KgCTL9iSwHV5f3HOUMlcYgvsvqyf4Tcj9c1ddMyBVC0k43hS0RIUXpfrGcZ0Pt4C8A13YthJhh0XzuHAXTmbnxg+2T/O/b+9kEJLJli/DLH1LAY6d2u/ZyTCdoQg9O2n+wFX5Y+jcF3vYE2St4w8pWQ4NaZihQVoiDKG76B9u/DBaEinMGcptL3utkYw7LgV9Iq5mLF1x49FBWM5uoKPeXKuS+DmDWLuG8RCnKuNpJa67fx8xzqwp+WUNgzx9H6lGmpnv1EWLamoD2EJzzwsAOfKC7QDOOd5MZp2Q/L8v//////////////////////////////IEFBNtCMXtK/O6BIr+bcrrr+////////////////////wAGz+F+j7kvGmqoo/paCJBK88bpPixgulzS/1e0EryaK7OMxqGTEg7iz0WBScD7nHJFBX9YaMoXkYDshGShqOry3i7ZC7cH8+Eu9RPAAfbOzXdcnomQhvS9vsXnYPfXlozbsu96eyioE0T5YYvnE/PeLPzKio07NBR1CT/xg19Ev8xxiGzmWJvA0DQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABgAJBQTbQjF7SvzugSK/m3K66/v///////////////////wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAKBEg44oVA/SbSYxb2oc8MuxQfNW+T1l+bFm8aB1RxnnYOCbKAZvaR/d0CRXs25XXX9////////////////////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAcAAAAIACgRIOOKFQP0m0mMW9qHPDLsUHzVvk9ZfmxZvGgdUcZ52DgmygGb2kf3dAkV7NuV11/f///////////////////wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIACQUE20Ixe0r87oEiv5tyuuv7///////////////////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIACHWbRr9FCFq3KVx6zIcPByRc4/Q/0/ppQxIyUlJnpFbJKiDc3oZyADuwmQpNiFDjr/kUDdwI8XzIXgStCIahqx5pfT5dIXhH66bBRZOD3u0zfM83I/7O+IaK4xxyF6+pjROF9RNIoeTbAHqBJo3/jVwyuhJnfIvGse5zY/IIicHX/zaDqhLz4p3Okbgvo3D48g843ozJXKFXMEz/YdfTLPIfYRo6lCTxNAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIACDRjsOmzY6mq9HPCoAky/YksB1eX9xzlDJXGIL7L6sn+E3I/XNXXTMgVQtJON4UtESFF6X6xnGdD7eAvANd2LYSYYdF87hwF05m58YPtk/zv2/vZBCSyZYvwyx9SwGOndrv2ckwnaEIPTtp/sBV+WPo3Bd72BNkreMPKVkODWmYoUFaIgyhu+gfbvwwWhIpzBnKbS97rZGMOy4FfSKuZixdcePRQVjObqCj3lyrkvg5g1i7hvEQpyrjaSWuu38fMc6sKfllDYM8fR+pRpqZ79RFi2pqA9hCc88LADnygu0AzjneTGadkPy/L//////////////////////////////wDgAQAAgAJ90WoBNmdax+v1JKsTOnGlqkLqt+TBQ0VhR+ZRf31F/KMdLIbg2gI6jQJnyGEz9JY9gfgIu+JELDEELic4n3i8YcXSB66LPHDBGINN+jgwOZyOMV4y4ZXclz1LqYyJ5HCjx5sfg6hm3+R8m3qyVS4fGxzPuAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAKz+hbVx0jPbZklgTYDN80D7Kxzifnv1LMtuDFcadBKgdvK2ZoAA63LrVl0HXsQay1Ls0BEyNSO+ICgzzKoZOM7Dr3ffcoexau+qtedrtLLii/Zn7mDKaykfmePmQcyTmX161JGCvLDGrt7ezfzMTGqlUXYWf//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////gAITBJ99oVyeOcIreXAc+MxJG6IPLr3lJsCWld5rFD/rN57z1xvNjx7b9Fr/5mQO6ZTXyDsAqCXxpU035NmSPvqbdmKcHLYulsMuwjhWSz8xrkYInENQ/a183k49kgPCV95fTEr940pls3fNvSB5EtcGTzEtuAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAINGOw6bNjqar0c8KgCTL9iSwHV5f3HOUMlcYgvsvqyf4Tcj9c1ddMyBVC0k43hS0RIUXpfrGcZ0Pt4C8A13YthJhh0XzuHAXTmbnxg+2T/O/b+9kEJLJli/DLH1LAY6d2u/ZyTCdoQg9O2n+wFX5Y+jcF3vYE2St4w8pWQ4NaZihQVoiDKG76B9u/DBaEinMGcptL3utkYw7LgV9Iq5mLF1x49FBWM5uoKPeXKuS+DmDWLuG8RCnKuNpJa67fx8xzqwp+WUNgzx9H6lGmpnv1EWLamoD2EJzzwsAOfKC7QDOOd5MZp2Q/L8v//////////////////////////////AYACfdFqATZnWsfr9SSrEzpxpapC6rfkwUNFYUfmUX99RfyjHSyG4NoCOo0CZ8hhM/SWPYH4CLviRCwxBC4nOJ94vGHF0geuizxwwRiDTfo4MDmcjjFeMuGV3Jc9S6mMieRwo8ebH4OoZt/kfJt6slUuHxscz7gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIACs/oW1cdIz22ZJYE2AzfNA+ysc4n579SzLbgxXGnQSoHbytmaAAOty61ZdB17EGstS7NARMjUjviAoM8yqGTjOw69333KHsWrvqrXna7Sy4ov2Z+5gymspH5nj5kHMk5l9etSRgrywxq7e3s38zExqpVF2Fn//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////4ACEwSffaFcnjnCK3lwHPjMSRuiDy695SbAlpXeaxQ/6zee89cbzY8e2/Ra/+ZkDumU18g7AKgl8aVNN+TZkj76m3ZinBy2LpbDLsI4Vks/Ma5GCJxDUP2tfN5OPZIDwlfeX0xK/eNKZbN3zb0geRLXBk8xLbgEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALsAAAB2AQAAgAIFm9NfhUXfr6A++EqNACQVGuLtgNgLX1VUpCFGUgVN4BwNEe4jdB/rVtzZeKMBZDvvB7ndukKdOgpoigfUejk2nh0w5uOSpacj1LZYeoX+kDBs0OzQ/ZhCjnYoR4cGMJelGPlN2rb1BfG1yqNjy8e4HD2+XgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAJzFvJX3vwfqtmUWxwfn9AHa8MWc+TPtA3HTqfUP+LEdwWSSDeYwEIYsxMVFnmKJyAau2CsBivB2E1oEOZInoJhvHwohLB3XcbN6czTYxyhDtkzFxw++BOINoiYVVmvlLRjzXecowdRoCN/JTyF/6azYDrYqP//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////gAL7MsZiEL4KNYsL5wGVdBnstbyXPDHESjgu44t/KhuBiz2zpP/QjV6SugP3iyH065QgQuKWxf4sDKGtquPsXrmjYJxmEq1lxf9VoSLXLiKSQMuHpAfFOapaLqdABzmFcN4GVGX41XsnoE+fhWDh46NEpmvn/wgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAJXWr1AiFZWn+BaYjatJjIbWQn4NMB8gcYg/P4croFR69TsaGvpBHJmQ5bjmhW48Hc2DEYmx+EOAyCFV31hPR23kDyiOmtUnCsVdq5zSIXEXXlWtz2HnRtzpv9GerCyQjXAGPocmgcbUdtvwQOHvAqAcHHoqwEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAL9we9SQce072hZ8O/UQRsRo7jUjcQ/cja5GoNW+QtDkroXDOGjjuIWAVsd4IHL1SVMeW2kmYUpFReTOxo6Z++11AkTlFQWVs8cW5Zdkzizhg+J+zP41ms4N5Km/TNVABGx/urrKoJlIfiMreE+hPgQfqnxWgEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAKZz3G9f0b56FG9blPowul7ytAcWHKx5c6tCvJkXvp/kriFAFJL8n4csobNSc+tX92G/Deca1YrGqv1Hf1pDfq6QLV3I1+E7nMbm55/vmU4LCE9PFyUTfjkBigySt7902zC0IxCc+matQ2aG7I3tXr4d4z+PwIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgALJaotK/L1Up/DtElIjBy4MWxJ/7PCf0nveeqr/rKIN/05nz0ZhXX2NZt1KDs35qV1PWj2KpcXGxwehcgakidpfGcJHOM0RDMRhVRgR7L2g2DW3inci8yF9IlTxhTp2MfwgWAB8pKoSehINfT48DFk6GQ4jNAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAITq5AHksyD+dlPUYJA9xZNPrJO+Sz2TIFfBa3GrUZ6HfzSUF6jBGDTDiGRBpIfSvOGIIM/vEUtMSAqz2w78XzwKN/vADPPthXSy9e1OwfFJErgHuAkCcttexY8W1DBYOhjx++AotvTMjK+FYsb6uuIE25NAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAKfQCjfVMf1g23blYSd2PnIm8cVZT9sVwRjGgl0Q/GWj45wjUr0sa7w5vFe14hfjwwJ91caaaAh8o+g1O7C1/tcLC1/eSmYKvsXg4B3zWmjIbUppTR1WnDuJGQGEDwrVqNwX2MJGpBTN6xNBmhvJRCaNCRHNhAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4AEAAOABAAAAgAKTmnFrKKZcK6Sl/tfq/z6NrN/HZAFsMIrK3vi34zSpL7aU5JvIE/vhcoPVKymh5Jw5vL51VlxFspPyGMtU29TCaZKVbtxht3Wepx8Ge34sqnzemHL1HsBXlNL0EgPiEWqMEasoqWb0qOkPKg9tflJV7R6QjwEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAI/rhrBqLFWli8iNktWWzCawbmW6N6E9hqYVS+24JTUUk3IvlnWKvkmYnRx1crQfGGwPA5+9ZfwhSHOxCePbNJorofKurF0Aefe/Dv85Jf2f6WjNLNMb9G7DzntD0AcW2dbtPYcnidf49sCcNXeOdcpICC3Wv//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////gALPLpQAfUg/oIER0fhhw2qotznACcd7XIE4yWCERCJtJynNL5hY6mNM2OwkaKl/sKcyc9j1RP/vPCrqukyW9MoyWf5hsLYisSC1BjHjKsCmnSd6avK3IdVHJ43v6mX6Cwgr93+93rhclsvog3QGK0wrOISiLgIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAINGOw6bNjqar0c8KgCTL9iSwHV5f3HOUMlcYgvsvqyf4Tcj9c1ddMyBVC0k43hS0RIUXpfrGcZ0Pt4C8A13YthJhh0XzuHAXTmbnxg+2T/O/b+9kEJLJli/DLH1LAY6d2u/ZyTCdoQg9O2n+wFX5Y+jcF3vYE2St4w8pWQ4NaZihQVoiDKG76B9u/DBaEinMGcptL3utkYw7LgV9Iq5mLF1x49FBWM5uoKPeXKuS+DmDWLuG8RCnKuNpJa67fx8xzqwp+WUNgzx9H6lGmpnv1EWLamoD2EJzzwsAOfKC7QDOOd5MZp2Q/L8v//////////////////////////////AYACk5pxayimXCukpf7X6v8+jazfx2QBbDCKyt74t+M0qS+2lOSbyBP74XKD1SspoeScOby+dVZcRbKT8hjLVNvUwmmSlW7cYbd1nqcfBnt+LKp83phy9R7AV5TS9BID4hFqjBGrKKlm9KjpDyoPbX5SVe0ekI8BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIACP64awaixVpYvIjZLVlswmsG5lujehPYamFUvtuCU1FJNyL5Z1ir5JmJ0cdXK0HxhsDwOfvWX8IUhzsQnj2zSaK6HyrqxdAHn3vw7/OSX9n+lozSzTG/Ruw857Q9AHFtnW7T2HJ4nX+PbAnDV3jnXKSAgt1r//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////4ACzy6UAH1IP6CBEdH4YcNqqLc5wAnHe1yBOMlghEQibScpzS+YWOpjTNjsJGipf7CnMnPY9UT/7zwq6rpMlvTKMln+YbC2IrEgtQYx4yrApp0nemrytyHVRyeN7+pl+gsIK/d/vd64XJbL6IN0BitMKziEoi4CAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALsAAAB2AQAAgALJW0UVZhVGqnNi2iqJj6fUTJN4+x96thu5YJ6LJeOk0hCYcS9zuDoBkI4GVyLMZXf/DyoqsdBT13OpJHu9TqtbzYJ17gz1uHLTZ8saLZp4a5BtECrzkmQxtk8h/A6sJwKBx6UHqXF4QdMbC/UVd/vkjbveNgEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAJFWI1xsx8JxQQdFxHhwY8v8QHGFWYALPI7p4+h2r/H3SAUGjqOEEsuH0w+odq2k4BfWJQTcU9mPBdetS2e/DPtYI5LDKqumVyYtrYZmx6SxhvORTy2TFUDiX6S/wUKgG1YKSslKoyZeKgQ97ShBdzmdp4tC///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////gAILocVYwkYfbygxeVF2SKSq8K0EjnMsAqVUPO+h84RfhV+Df8aK8RESn2q5wxAl5meaqVw34erJsFXatQhcVCao1oRlMCcBNp/vxs9Vt6qfDYqDxSvxOeDEBeol+DTIqDUdfW6sTvbbOymAopDpZPocQYg/6AIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAL1NPaSrthZp271/I2CAdiCw6N+/bqb/ZltfcdwVF8Wdnz6LRVoXwcn80PFGdO6QJpBoAZVOo0ZHDs4yuS9DgfidPiDZFh+P0sCjJ6/BtiEKBLvWn8VIornWiClJqOj9JdrRLqO2hoHkz1UWpD5yupH+LFNNQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAI70XqrT10/X+SBr5IK7a024s4wq5xHxfd/EHGX38NZqcs17OxuILHlRIdIYvvAUckrLrj3DjiWn0rivqof2RdO237c/VvPmhqiKiQmn8vdx6xtcrDs++ClgwvPQNqQvsdFiAL+FsVpzv8iBlMNXZGKdJ/AzP//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////gAJ3wUE/5hy40/JxvBhis2VD1N2KtpzoINMU66mM3XJyLlyCiuYInCqThB880XsfDZ22j2xVe+TA7eLqmQUugp7VExE8msL19UIir6qnYMGOHOKHQHR+Keun1P5NzixjBU6gigYjwFsf5H7VCGfyK3tdOeO25w8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAJ1dzo4ZmfTrb/v1d1jaAPUi8m/coWsdAAubAABlQuJYcHRRfqEWbhcWj5SH3+VKmklHO9bgz6Sr1zL4orKQ+K0PI93NZyWJr+DHm5G5xkjortbC7HkaBRYa67J1MqKWcAonePXGawFksvj1vMjvU2eaxHp5wEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAJlw0LGvWRU9UQIjZ4EAb2MmbT78YXAgv+uGg8wtSpXGbyEB3HWQp74V82T/d0Vxo0WThtSg2jomBJu24xNk8GlqRTNB3V4/0zMsY9F/exiEh8U7OVPn4zMtjV9X0CNv9tdLQjoLtj8bA4X8Ad1QSswo7Xzkv7/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////gAJH8tMXH6z0wP5zgFS6ItKnG2wqYV20VYHxaqOZgrpIsIVvA0SPSYPh9tw4t0i7UI4GdWZmfH+XUPo1xI0btewTfaYKF00rgdSPtBYWxW/cpRZ54QCUkwvSQENehBoXmg/ArTU0vmjEU+Fxz9dU3lZKq53D/wEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4AEAAOABAAA=',
			'base64',
		);
		let encryptedSecretShare = encrypt_secret_share(
			Buffer.from(dkgFirstRoundMock.centralizedSecretKeyShare, 'base64'),
			encryptionKey,
		);
		console.log('encryptedSecretShare', encryptedSecretShare);
	});
});
