[package]
name = "eth-light-client-wasm"
edition = "2021"
version = "0.1.0"
license = "BSD-3-Clause-Clear"
publish = false

[dependencies]
bcs = "0.1.6"
helios = { git = "https://github.com/dwallet-labs/helios" }
hex = "0.4.3"
serde_json = "1.0.128"
serde = "1.0.210"
anyhow = "1.0.89"
eyre = "0.6.12"
serde-wasm-bindgen = "0.6.5"
wasm-bindgen = "0.2.92"
wasm-bindgen-futures = "0.4.43"
ethers = "2.0.14"
light-client-helpers = { path = "../../crates/light-client-helpers" }

[dev-dependencies]
dirs = "5.0.1"

[lib]
crate-type = ["cdylib"]