[package]
name = "sui-graphql-rpc-headers"
version = "0.1.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "BSD-3-Clause-Clear"
publish = false
edition = "2021"

[dependencies]
axum.workspace = true

workspace-hack.workspace = true
