[package]
name = "ika-network"
version = "0.0.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "BSD-3-Clause-Clear"
publish = false
edition = "2024"

[dependencies]
anemo.workspace = true
anemo-tower.workspace = true
governor.workspace = true
serde.workspace = true
tonic.workspace = true
dashmap.workspace = true
tower.workspace = true

ika-archival.workspace = true
sui-types.workspace = true
ika-types.workspace = true
ika-config.workspace = true

bcs.workspace = true
fastcrypto.workspace = true
mysten-common.workspace = true
mysten-network.workspace = true
tokio = { workspace = true, features = ["full"] }
tracing.workspace = true
futures.workspace = true
tap.workspace = true
rand = "0.8" # use old version for compatability with fastcrypto
anyhow.workspace = true
prometheus.workspace = true
mysten-metrics.workspace = true

[build-dependencies]
anemo-build.workspace = true

[dev-dependencies]
telemetry-subscribers.workspace = true
tokio = { workspace = true, features = ["test-util"] }
ed25519-consensus.workspace = true
