name: Build Docker image

on:
  push:
    branches:
      - main
      - new-main
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

env:
  RUST_BACKTRACE: 1
  # Change to specific Rust release to pin or `stable` for the latest stable version.
  rust_stable: 1.85
  rust_nightly: nightly
  CARGO_NET_GIT_FETCH_WITH_CLI: true
  GITHUB_TOKEN: ${{ secrets.GH_PRIVATE_REPO_TOKEN }}
  DOCKER_TAG: ika:devnet-v0.0.6-arm64

jobs:
  build-docker-image:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          cd sdk/typescript/test/chaos-test/
          chmod +x ./build.sh
          ./build.sh

      - name: Save Docker image as tar
        run: docker save ${{ env.DOCKER_TAG }} -o image.tar

      - name: Upload image artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: image.tar
