name: E2E test CI

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

env:
  RUSTDOCFLAGS: -Dwarnings
  RUST_BACKTRACE: 1
  # Change to specific Rust release to pin or `stable` for the latest stable version.
  rust_stable: 1.79
  rust_nightly: nightly
  CARGO_NET_GIT_FETCH_WITH_CLI: true
  GH_PRIVATE_REPO_TOKEN: ${{ secrets.GH_PRIVATE_REPO_TOKEN }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os:
          - x86_64-unknown-linux-gnu
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Configure git with personal access token
        run: |
          git config --global url."https://x-access-token:${{ env.GH_PRIVATE_REPO_TOKEN }}@github.com/".insteadOf "https://github.com/"
      - name: Install Rust ${{ env.rust_stable }}
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.rust_stable }}
          targets: ${{ matrix.os }}
      - name: Install Target
        run: rustup target add ${{ matrix.os }}
      - uses: Swatinem/rust-cache@v2
      - name: Build
        run: cargo build --bin pera --target ${{ matrix.os }}
      - name: Run the test validator
        run: |
          screen -dmS sui-test-validator-session ./target/debug/pera start --with-faucet --force-regenesis --epoch-duration-ms 1000000000000
          sleep 5
          SUI_PID=$(pgrep -f 'pera start' | head -n 1)
          echo "Captured PID: $SUI_PID"
          echo "SUI_PID=$SUI_PID" >> $GITHUB_ENV
      - name: Terminate the test validator
        run: |
          kill $SUI_PID