[package]
name = "ika-types"
version = "0.1.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "BSD-3-Clause-Clear"
publish = false
edition = "2021"

[lints]
workspace = true

[dependencies]
dwallet-mpc-types.workspace = true
group.workspace = true
anemo.workspace = true
anyhow.workspace = true
bcs.workspace = true
byteorder.workspace = true
consensus-config.workspace = true
once_cell.workspace = true
prometheus.workspace = true
rand.workspace = true
serde.workspace = true
serde-name.workspace = true
thiserror.workspace = true
tracing.workspace = true
serde_json.workspace = true
serde_with.workspace = true
static_assertions.workspace = true
schemars.workspace = true
tap.workspace = true
tonic.workspace = true
strum.workspace = true
strum_macros.workspace = true
roaring.workspace = true
enum_dispatch.workspace = true
eyre.workspace = true
jsonrpsee.workspace = true
move-core-types.workspace = true
class_groups.workspace = true
mpc.workspace = true
twopc_mpc.workspace = true
ika-protocol-config.workspace = true
shared-crypto.workspace = true
mysten-network.workspace = true
sui-macros.workspace = true

fastcrypto = { workspace = true, features = ["copy_key"] }
fastcrypto-zkp.workspace = true

typed-store-error.workspace = true
derive_more = { workspace = true, features = ["as_ref", "debug", "display", "from"] }
sui-json-rpc-types.workspace = true
sui-config.workspace = true

sui-types.workspace = true
serde_repr.workspace = true
rand_chacha = "0.3.1"
base64.workspace = true

[dev-dependencies]

[features]
default = []
test-utils = []
