[package]
name = "sui-proc-macros"
version = "0.7.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "BSD-3-Clause-Clear"
publish = false
edition = "2021"

[lib]
proc-macro = true

[dependencies]
quote.workspace = true
syn = { version = "2", features = ["full", "fold", "extra-traits"] }
proc-macro2.workspace = true
sui-enum-compat-util.workspace = true
workspace-hack.workspace = true

[target.'cfg(msim)'.dependencies]
msim-macros.workspace = true
