[package]
name = "sui-swarm-config"
version = "0.0.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "BSD-3-Clause-Clear"
publish = false
edition = "2021"

[dependencies]
anemo.workspace = true
anyhow.workspace = true
fastcrypto.workspace = true
rand.workspace = true
serde.workspace = true
serde_with.workspace = true
serde_yaml.workspace = true
tempfile.workspace = true
tracing.workspace = true
prometheus.workspace = true

move-bytecode-utils.workspace = true
narwhal-config.workspace = true
shared-crypto.workspace = true
sui-config.workspace = true
sui-protocol-config.workspace = true
sui-types.workspace = true
sui-genesis-builder.workspace = true
workspace-hack.workspace = true

[target.'cfg(msim)'.dependencies]
sui-simulator.workspace = true

[dev-dependencies]
insta.workspace = true
tempfile.workspace = true

sui-execution.workspace = true
